### ISSUE TITLE
褚老师好，请问第二课，词向量训练完成后，保存在哪个文件，如何读取呢？

### ISSUE THREAD

**Issue by Wenwen717** [ZeweiChu/PyTorch-Course#2]
`model.load_state_dict(torch.load("embedding-{}.th".format(EMBEDDING_SIZE)))`
是词向量保存在embedding-{}.th这个文件中吗？
`TEXT.build_vocab(train_data, max_size=25000, vectors="glove.6B.100d", unk_init=torch.Tensor.normal_)`
可以像打开glove词向量的方式打开它吗？？

**Comment by ZeweiChu** [comment]
load_state_dict 是 读入模型。请参考这份tutorial https://pytorch.org/tutorials/beginner/saving_loading_models.html
